### ISSUE TITLE
ReferenceError: awslambda is not defined

### ISSUE THREAD

**Issue by mainfraame** [H4ad/serverless-adapter#118]
## Current Behavior

Fails to compile with `@h4ad/serverless-adapter/lib/handlers/aws`:

```
ReferenceError: awslambda is not defined
```

there's a few references in that file:

https://github.com/H4ad/serverless-adapter/blob/main/src/handlers/aws/aws-stream.handler.ts#L116

the compiled code that is packaged in the node-module ends up with references to `awslambda`'s methods, but no reference to where that comes from.

**Comment by H4ad** [comment]
Some questions:

- Are you having this issue during compilation or in runtime (executing the code)?
  - If is during the compilation, so this could be a bug.
- Are you using AWS Lambda with Stream mode configured? `RESPONSE_STREAM` instead of `BUFFERED`?
  - If not, just change to `RESPONSE_STREAM` and it should work.

If you don't want to use the `RESPONSE_STREAM`, use the [DefaultHandler](https://serverless-adapter.viniciusl.com.br/docs/main/handlers/aws#usage) instead of `AwsStreamHandler`, the last one is only intended to be used when `RESPONSE_STREAM` is configured.

**Comment by mainfraame** [comment]
it's not related to any of that. if you look at the transpiled output that is published to npm (handlers/aws/aws-stream.handler.js), you'll see two spots where `awslambda` is undefined:

```
class AwsStreamHandler extends import_core.BaseHandler {
  getHandler(app, framework, adapters, resolverFactory, binarySettings, respondWithErrors, log) {
    return awslambda.streamifyResponse(async (event, response, context) => {    // <------------------------- HERE
      const streamContext = { response, context };
      this.onReceiveRequest(log, event, streamContext, binarySettings, respondWithErrors);
      const adapter = this.getAdapterByEventAndContext(event, streamContext, adapters, log);
      this.onResolveAdapter(log, adapter), (0, import_core.setCurrentInvoke)({
        event,
        context
      }), await this.forwardRequestToFramework(app, framework, event, streamContext, adapter, binarySettings, log);
    });
  }
```

and...

```
async forwardRequestToFramework(
    app,
    framework,
    event,
    context,
    adapter,
    binarySettings,
    log
  ) {
    const requestValues = adapter.getRequest(event, context, log);
    this.onResolveRequestValues(log, requestValues);
    const request = new import_network.ServerlessRequest({
        method: requestValues.method,
        headers: requestValues.headers,
        body: requestValues.body,
        remoteAddress: requestValues.remoteAddress,
        url: requestValues.path
      }),
      response = new import_network.ServerlessStreamResponse({
        method: requestValues.method,
        onReceiveHeaders: (status, headers) => {
          const flattenedHeaders = (0, import_core.getFlattenedHeadersMap)(
              headers
            ),
            awsMetadata = { statusCode: status, headers: flattenedHeaders },
            cookies = headers['set-cookie'];
          cookies &&
            ((awsMetadata.cookies = Array.isArray(cookies)
              ? cookies
              : [cookies]),
            delete headers['set-cookie'],
            delete flattenedHeaders['set-cookie']),
            this.onForwardResponseAdapterResponse(log, awsMetadata);
          const finalResponse = awslambda.HttpResponseStream.from(     // <----------- HERE
              context.response,
              awsMetadata
            ),
            isHundreadStatus = status >= 100 && status < 200,
            isNoContentStatus = status === 304 || status === 204,
            isHeadRequest = requestValues.method === 'HEAD';
          return (
            (isHundreadStatus || isNoContentStatus || isHeadRequest) &&
              (finalResponse.write(''), response.end()),
            finalResponse
          );
        },
        log
      });
    framework.sendRequest(app, request, response),
      log.debug(
        'SERVERLESS_ADAPTER:FORWARD_REQUEST_TO_FRAMEWORK:WAITING_STREAM_COMPLETE'
      ),
      await (0, import_core.waitForStreamComplete)(response),
      log.debug(
        'SERVERLESS_ADAPTER:FORWARD_REQUEST_TO_FRAMEWORK:STREAM_COMPLETE'
      ),
      context.response.end();
  }
```

**Comment by H4ad** [comment]
`awslambda` is a global variable that is defined when you deploy your lambda with Stream support.

If you don't want to use stream support, change the handler to `DefautlHandler` and remove all the references for `@h4ad/serverless-adapter/lib/handlers/aws`.

If you want to use stream support, you can try searching to see how you can make the webpack ignore that global variable because it will be defined when you run that code on Lambda.

I only have time tomorrow to do more tests but if you have time, you can open a PR to use `global.awslambda` instead of `awslambda`, this will probably solve the issue with webpack too.

**Comment by H4ad** [comment]
Closing this one since I think the issue was solved and is more likely to be a problem with the bundler configuration.
